version: '3.9'
services:
    ngen-postgres:
        image: "postgres:latest"
        restart: always
        environment:
            - POSTGRES_PASSWORD=example
            - PGDATA=/var/lib/postgresql/data
        volumes:
            - ./postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
    ngen-adminer:
        image: adminer
        restart: always
        ports:
            - "8080:8080"
    ngen-django:
        image: ngen:latest
        build:
            context: ../
            dockerfile: docker/Dockerfile
        restart: always
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ../:/code
        ports:
            - "8000:8000"
        environment:
            - POSTGRES_NAME=ngen
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=example
            - POSTGRES_HOST=ngen-postgres
            - CELERY_BROKER_URL=amqp://guest:guest@ngen-rabbitmq:5672
        depends_on:
            - ngen-postgres
            - ngen-rabbitmq
    ngen-rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
            - "5672:5672"
            - "15672:15672"
    ngen-celery:
        image: ngen:latest
        restart: always
        command: celery -A djangoProject worker -l debug
        volumes:
            - ../:/code
        environment:
            - CELERY_BROKER_URL=amqp://guest:guest@ngen-rabbitmq:5672
        depends_on:
            - ngen-django
            - ngen-rabbitmq