name: Ngen CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    env:
      container_name: docker_ngen-django_1
    steps:
    - uses: actions/checkout@v2
    - name: Build docker containers
      run: |
        cd docker
        docker-compose build
        docker-compose up -d

        max_retries=30
        retries=0
        while [[ "$(docker inspect -f '{{.State.Running}}' "$container_name")" != "true" ]]; do
          retries=$((retries + 1))
          if [ $retries -ge $max_retries ]; then
            echo "Service did not become healthy within the timeout."
            exit 1
          fi
          sleep 2
        done
    - name: Run tests
      run: |
        docker exec -it "$container_name" ./manage.py test ngen.tests
